/* ─────────────────────────────────────────────────────────────
   LUPA 강의 영어 번역 사전 — embeddedpro202601_01_lupastudio.html
   KO/EN 토글용. 본 파일은 데이터만 담고, 적용 로직은 본문 HTML의
   <script> 마지막 부분(applyLang)이 담당한다.
   ───────────────────────────────────────────────────────────── */
var LANG_EN = (function() {
  'use strict';

  /* ── UI 문구 ─────────────────────────────────────────────── */
  var UI = {
    /* 등록 모달 */
    'modal.h3': 'Learner Registration',
    'modal.p': 'Your progress is recorded with your company mail ID. Chapter progress and quiz results are saved,<br>so you can resume learning anytime.',
    'modal.uid.ph': 'Mail ID (required)',
    'modal.err': 'Enter only the mail ID — e.g. sophiahj.lee',
    'modal.name.ph': 'Name (required)',
    'modal.dept.ph': 'Department / Team (optional)',
    'modal.skip': 'Skip',
    'modal.start': 'Start',

    /* 좌측 레일 */
    'rail.title': '[1] Understanding LUPA Studio and the Environment',
    'rail.meta': 'Instructor: Yun-Gwan Kim, Senior Research Engineer',
    'rail.progMain': 'Progress {done} / {total}',
    'rail.progSubPending': '{n} quizzes incomplete',
    'rail.progSubAll': 'All completed',
    'rail.progSubLeft': '{n} chapters remaining',
    'rail.progSubStart': 'Get started',
    'rail.back': '← Lecture list',
    'rail.quiz': 'Quiz',
    'rail.min': '{n} min',

    /* 상단 바 */
    'topbar.prog': 'Progress',
    'topbar.crumb': 'CHAPTER {nn} / {total} &nbsp;·&nbsp; <b>{title}</b>',

    /* 플레이어 */
    'player.playRange': 'Play this section',
    'player.scriptHead': 'Lecture transcript',
    'player.lines': '{n} lines',
    'player.mockNote': 'Play from this point · In the deployed environment, playback starts right here',
    'player.play': 'Play',

    /* 거터 */
    'gutter.aria': 'Adjust video area width',
    'gutter.title': 'Drag to adjust video width · Double-click for default · Also adjustable with ← → keys',

    /* 하단 액션 바 */
    'actions.prev': '← Previous chapter',
    'actions.next': 'Next chapter →',
    'actions.quizNote': 'Your progress is <b>recorded</b> only when you pass the quiz.<br>If you skip, it stays as <b>quiz incomplete</b> in the table of contents.',
    'actions.quizBtn': 'Knowledge check {n} questions →',
    'actions.noQuizNoteLast': 'This chapter has no quiz.<br>Press Complete to <b>finish immediately</b>.',
    'actions.noQuizNoteNext': 'This chapter has no quiz.<br>Moving on will <b>complete it immediately</b>.',
    'actions.finish': 'Finish learning',
    'actions.nextFinish': 'Next chapter',
    'actions.tick': 'Progress +1',

    /* 퀴즈 */
    'quiz.backToLearn': '← Learning screen',
    'quiz.checkLbl': 'CH.{nn} knowledge check',
    'quiz.qno': 'QUESTION {n} / {m}',
    'quiz.explain': 'Explanation',
    'quiz.replay': 'Replay this chapter section',
    'quiz.nextQ': 'Next question →',
    'quiz.showResult': 'Show result →',
    'quiz.perfect': 'Perfect',
    'quiz.passed': 'Passed',
    'quiz.failed': 'Below the passing standard',
    'quiz.passSub': 'Review the explanations of the questions you missed, then move on to the next chapter.',
    'quiz.failSub': 'The passing standard is {pct}%. Check the explanations and try again.',
    'quiz.reflected': 'Reflected in your progress',
    'quiz.notReflected': 'Not reflected in your progress',
    'quiz.retry': 'Try again',
    'quiz.learnScreen': 'Learning screen',
    'quiz.nextCh': 'Next chapter →',

    /* 학습자 */
    'user.change': 'Change',

    /* 챕터 본문 라벨 */
    'mod.goals': 'Goals',
    'mod.keys': 'Key points',
    'ch.sub': '{m} min · {g} goals · {k} key points'
  };

  /* ── 챕터 제목 ───────────────────────────────────────────── */
  var CH_TITLE = [
    'Instructor Introduction and Course Overview',
    'LUPA Studio and Development Environment: Key Menus and Features',
    'SDK Manager, Emulator, Device Manager, and Serial Port Management',
    'Quick Launcher and Status Bar: Layout and Information Display',
    'LUPA Application Project Structure and Configuration',
    'LUPA Application Development Process, System Apps, and Package Naming Rules',
    'Device Connection and Debugging in the LUPA Development Environment',
    'Non-GUI Service Templates and the Project Wizard',
    'Application Debugging and launch.json Configuration'
  ];

  /* ── 챕터별 학습목표(goals) / 주요내용(keys) ─────────────── */
  var CH_GOALS = {
    '0': [
      'Explain the role and features of LUPA Studio.',
      'Understand and describe the LUPA Application development procedure using LUPA Studio.',
      'Explore development-related information using the LUPA developer site and the LUPA AI chatbot service.'
    ],
    '1': [
      'Understand and describe the key menus and features of LUPA Studio.',
      'Set up the LUPA Application development environment using LUPA Studio.',
      'Learn the roles and usage of each menu: SDK Manager, Device Manager, Repository, Quick Launcher, etc.',
      'Check project and build information via the LUPA Studio Status Bar.'
    ],
    '2': [
      'Install, activate, and manage SDKs using the SDK Manager in LUPA Studio.',
      'Run the Emulator and configure it for various SDKs and target images.',
      'Add and manage serial ports and devices, and install apps via the Device Manager.',
      'Use Custom SDK and User Emulator features in LUPA Studio to work with locally built images.'
    ],
    '3': [
      'Run frequently used commands with the Quick Launcher in LUPA Studio.',
      'Check development environment information such as project, device, SDK, target, and build info via the Status Bar.',
      'Understand the execution conditions of each Quick Launcher command (debug state, target selection, etc.) and use them appropriately.',
      'Use auxiliary features of LUPA Studio such as the API guide viewer and the LDB terminal.'
    ],
    '4': [
      'Explain the basic structure of a LUPA application project and the roles of key folders and files.',
      'Understand and describe the purpose and usage of key configuration files such as manifest and spec.ini.',
      'Distinguish the life-cycle differences by LUPA application type (APP_TYPE_PERSISTENT, APP_TYPE_BACKGROUND, APP_TYPE_IMMORTAL, etc.).',
      'Explain how to add commands executed on install/uninstall to the spec.ini file and the precautions involved.'
    ],
    '5': [
      'Understand the LUPA application development procedure and create an actual project.',
      'Distinguish and apply the package naming rules for LUPA system apps and user apps.',
      'Create projects, build, run, and debug using LUPA Studio.',
      'Build and run LUPA apps considering SDK version and target chipset compatibility.'
    ],
    '6': [
      'Connect a device and the host PC in the LUPA development environment and perform debugging.',
      'Configure and use debugging methods appropriate for target device and emulator environments in LUPA Studio.',
      'Check the appOffset of a LUPA Application and load the symbol file at the correct location in gdb for debugging.',
      'Enter gdb commands directly in the debug console to check the debugging state and resolve issues.'
    ],
    '7': [
      'Create projects using Non-GUI service templates in LUPA Studio.',
      'Configure project location, template, SDK, target, etc. through the project wizard.',
      'Perform build, install, and run steps via the Quick Launcher and Device Manager in LUPA Studio.',
      'Verify the execution results of Non-GUI service apps via console output and the DMESG command.'
    ],
    '8': [
      'Create a launch.json file in LUPA Studio and add an application debugging configuration.',
      'Debug an application on a target device using the attach lupa-device configuration.',
      'Check and apply the J-Link device driver and OpenOCD settings.',
      'Set and verify the offset for correct symbol loading using the update-target-offset and meminfo commands.'
    ]
  };

  var CH_KEYS = {
    '0': [
      'LUPA Studio is an integrated development environment (IDE) for LUPA Application and platform development, provided as a Visual Studio Code-based Extension.',
      'LUPA Studio supports development, building, debugging, app installation, and execution through various features such as SDK Manager, Device Manager, Repository, and Quick Launcher.',
      'The LUPA developer site (lupa.lge.com, lupa.developer.lge.com) provides development guides and an AI chatbot service, and the chatbot can also be used inside LUPA Studio.',
      'The development cycle and application development procedure can be managed efficiently through LUPA Studio.',
      'The Device Manager manages emulators and real devices, and supports tasks such as app installation and execution, debugging, and log checking.'
    ],
    '1': [
      'LUPA Studio is provided as a Visual Studio Code-based Extension and is an IDE for LUPA Application development.',
      'The SDK Manager manages SDKs and emulators needed for development and provides activation and install/delete functions.',
      'The Device Manager manages real devices or emulators and supports various functions such as app installation, execution, and version checking.',
      'The LUPA Repository manages platform sources and build images, and displays custom SDK registration and build results.',
      'The Quick Launcher lets you quickly run frequently used commands such as build, install, run, and memory/register dumps.',
      'The GUI Library Manager manages GUI libraries used by the LUPA Application UI authoring tool.',
      'The Status Bar shows key development information such as project name, active SDK, target device, target platform, and build mode.'
    ],
    '2': [
      'In the SDK Manager you can install SDKs for the various versions of the LUPA platform and check their Activated and Installed states.',
      'A Custom SDK is an SDK built from the LUPA Repository and added to LUPA Studio; it is stored under the .lupastudio folder in your user directory.',
      'The Emulator works with the SDK to provide an app testing environment; the image changes automatically per target chipset (DQ-C, ITE, etc.), and the User Emulator feature lets you use locally built images.',
      'When the Emulator runs, three windows are provided: the Renode console, the UART0 terminal (system logs and console input), and the GDC window (UI display).',
      'The Device Manager manages real devices based on serial ports (COM ports) and emulators, and provides functions such as adding devices, naming ports, installing apps, and checking versions.',
      'Via the Status Bar and the Quick Select screen you can check build and debugging information such as the active SDK, target name, and debug availability.'
    ],
    '3': [
      'The Quick Launcher provides frequently used commands such as build, compilation, install, Start Application, and Uninstall as shortcut icons, with different execution conditions per command (target selection, app existence, debug state, etc.).',
      'The dump memory and dump register features are used in debug mode and can save the target device\u2019s memory and register values to files.',
      'The Status Bar shows key development environment information at a glance: LUPA project name, device name, active SDK, target name, build configuration, etc.',
      'A target name consists of platform, chipset, and product variant; when debugging symbols are included, \u201cdebug available\u201d is displayed.',
      'Status Bar items show the full name on mouse-over, and also include shortcuts such as build icons.',
      'The API guide viewer runs from the command palette and shows API documentation matching the SDK version; API information can also be found on the developer site and in chat.',
      'The LDB terminal is used in LUPA Studio for checking logs and running commands, and can be selected from the terminal in the Output panel.'
    ],
    '4': [
      'A LUPA application project consists of source and resource folders such as src, res, and ui, plus various configuration files such as CMake, manifest, and spec.ini.',
      'The manifest file specifies attributes such as the app\u2019s category and app type, and affects how the app runs and its life cycle.',
      'The spec.ini file specifies commands to run before/after install and uninstall in shell command format; due to size limits, only simple commands should be added.',
      'Depending on the app type (APP_TYPE_PERSISTENT, APP_TYPE_BACKGROUND, APP_TYPE_IMMORTAL, etc.), how the app starts and stops and its life cycle differ; with no type, the developer must control it directly.',
      'APP_TYPE_PERSISTENT always stays running and the system manages its life cycle directly; APP_TYPE_BACKGROUND keeps running in the background; APP_TYPE_IMMORTAL exits when its work is done.'
    ],
    '5': [
      'The LUPA application development procedure consists of repeating: project creation, UI work (if needed), service code writing, build, run, and debugging.',
      'The package naming rule is \u2018lupa.[app kind].[app name]\u2019; system apps use the \u2018sys\u2019 keyword and user apps use \u2018usr\u2019.',
      'LUPA Studio is a Visual Studio Code-based Extension; you can create projects with the Project Wizard and build, run, and debug using the Quick Launcher and launch.json.',
      'When building and running an app, you must check required information such as project selection, SDK version, and install location, and always consider SDK and target chipset version compatibility.',
      'System apps are included in the platform by default and handle essential functions; you can check installed and running app information with the meminfo command.'
    ],
    '6': [
      'In the LUPA development environment, you install Visual Studio Code and LUPA Studio on the host PC and debug by connecting to the target device.',
      'For device debugging, J-Link and OpenOCD are used, and gdb connects to the target device to perform the actual debugging work.',
      'In the emulator environment, instead of OpenOCD, gdb connects directly to the gdb server by port number for debugging.',
      'Check the appOffset of a LUPA Application via the lupa-update-target-at-offset command or the meminfo command, and align the symbol file load location in gdb.',
      'In the debug console, enter gdb commands such as info files to check whether the symbol file load location matches the appOffset.',
      'If the appOffset does not match, debugging will not work correctly, so when debugging problems occur, always check the appOffset and the symbol load location.'
    ],
    '7': [
      'LUPA Studio provides various templates for Non-GUI service (service app) development: empty project, hello world, event test, shell, etc.',
      'When creating a project with the project wizard, you can set location, template, app type, app ID, version, SDK, target, etc.',
      'Activate the SDK in the SDK Manager and select the build target in the Status Bar.',
      'Via the Quick Launcher, run build and execution commands in order: Clean, Configure, Build, Install Application, Start Application, etc.',
      'Manage target devices in the Device Manager, and check and run the list of installed apps.',
      'Non-GUI service apps do not show a UI on the target device, so check execution results via console output or the DMESG command.',
      'Use the LDB terminal and Shell Command to check logs and output from the target device.'
    ],
    '8': [
      'Create the launch.json file in the .vscode folder and add a debugging configuration such as attach lupa-device.',
      'Using the settings of the individual project directory rather than workspace settings prevents debugging environment conflicts.',
      'The J-Link device driver must be installed correctly; in LUPA development, J-Link is used through OpenOCD.',
      'Before debugging, run the update-target-offset command to save the app\u2019s offset information, and use the meminfo command to verify it was applied correctly.',
      'The appOffset is stored in the settings.json file and must match the meminfo result for symbols to load correctly.',
      'When starting debugging, attach first, add the application\u2019s breakpoints, and then enter the application code from the platform code.',
      'In the Run and Debug tab, select attach lupa-device and run the start-debug command to start debugging.'
    ]
  };

  /* ── 퀴즈 (44문항, 챕터별 배열) ──────────────────────────── */
  var QUIZ = {
    '0': [
      { q: 'In what form is the integrated development environment (IDE) provided by LUPA Studio applied to Visual Studio Code?',
        options: ['A separate executable', 'A web-based platform', 'A plugin', 'An Extension'],
        hint: 'LUPA Studio is provided as an extension of Visual Studio Code.' },
      { q: 'What is the main feature of LUPA Studio responsible for app installation and execution, debugging, and log checking?',
        options: ['Quick Launcher', 'SDK Manager', 'Device Manager', 'Repository'],
        hint: 'It is the feature responsible for device management.' },
      { q: 'Which of the following is NOT a service provided by the LUPA developer site?',
        options: ['App market', 'Chatbot integration inside LUPA Studio', 'Development guides', 'AI chatbot'],
        hint: 'The app market is not among the mentioned services.' },
      { q: 'Which of the following is NOT a feature of LUPA Studio supporting development, building, debugging, and app installation/execution?',
        options: ['SDK Manager', 'Device Manager', 'Task Scheduler', 'Repository'],
        hint: 'Task Scheduler is not among the main features of LUPA Studio.' },
      { q: 'What can be managed efficiently through LUPA Studio?',
        options: ['The application development procedure', 'Network configuration', 'Hardware design', 'Operating system installation'],
        hint: 'LUPA Studio focuses on managing the software development cycle.' }
    ],
    '1': [
      { q: 'Which feature is NOT provided by the SDK Manager?',
        options: ['Running apps', 'Installing SDKs', 'Deleting SDKs', 'Activating SDKs'],
        hint: 'The SDK Manager focuses on managing SDKs and emulators.' },
      { q: 'Which is NOT a feature supported by the Device Manager?',
        options: ['Version checking', 'Running apps', 'GUI library management', 'Installing apps'],
        hint: 'GUI library management is handled by a separate manager.' },
      { q: 'Which is NOT a feature provided by the Quick Launcher?',
        options: ['Memory dump', 'Custom SDK registration', 'Build', 'Register dump'],
        hint: 'Custom SDK registration is managed in the LUPA Repository.' },
      { q: 'Which information cannot be checked in the Status Bar?',
        options: ['Active SDK', 'Project name', 'Target device', 'GUI library version'],
        hint: 'The GUI library version is not shown in the Status Bar.' }
    ],
    '2': [
      { q: 'When adding a Custom SDK in LUPA Studio, where is the SDK file stored by default?',
        options: ['LUPA Repository server', '/opt/lupa/custom_sdk', 'C:\\Program Files\\LUPA\\SDKs', 'The .lupastudio folder under the user directory'],
        hint: 'Custom SDKs are stored in a hidden folder inside your home directory.' },
      { q: 'Which is NOT a window provided by default when running the Emulator?',
        options: ['Renode console', 'SDK Manager', 'UART0 terminal', 'GDC window'],
        hint: 'Three windows open automatically when the Emulator runs; an SDK management window is not among them.' },
      { q: 'What kind of port is the basis for managing real devices in the Device Manager?',
        options: ['Serial port (COM port)', 'USB port', 'Bluetooth port', 'Ethernet port'],
        hint: 'Real devices connect via UART serial (COM) ports. (The Emulator uses an Ethernet port.)' },
      { q: 'What must you change to change the product image before running the Emulator?',
        options: ['The active SDK in the SDK Manager', 'The Target Product in the Status Bar', 'The serial port in the Device Manager', 'The debug configuration in launch.json'],
        hint: 'When you change the target product in the Status Bar, the emulator image including the chipset changes automatically to match.' },
      { q: 'Which information cannot be checked in the Status Bar and Quick Select screen?',
        options: ['Emulator execution logs', 'Target name', 'debug available status', 'Active SDK'],
        hint: 'The Status Bar and Quick Select provide build and debugging related information.' }
    ],
    '3': [
      { q: 'Which is NOT information displayed in the Status Bar?',
        options: ['Device name', 'Build configuration', 'The size of debugging symbols', 'LUPA project name'],
        hint: 'The Status Bar shows key development environment information but not the size of debugging symbols.' },
      { q: 'Which is NOT a command provided by the Quick Launcher?',
        options: ['Uninstall', 'Start Application', 'Build', 'Dump memory'],
        hint: 'Dump memory is a feature used in debug mode.' },
      { q: 'Which is NOT an element that makes up a target name?',
        options: ['Platform', 'SDK version', 'Chipset', 'Product variant'],
        hint: 'A target name consists of platform, chipset, and product variant.' },
      { q: 'Which statement about the dump memory and dump register features is correct?',
        options: ['They run directly from the LUPA Studio Status Bar.', 'They save the target device\u2019s memory and register values to files.', 'They are available only in release mode.', 'They are provided by the API guide viewer.'],
        hint: 'These features are used in debug mode and save memory and register values to files.' },
      { q: 'How do you check the full name of an item in the Status Bar?',
        options: ['Double-click', 'Right-click', 'Shortcut key F1', 'Mouse-over'],
        hint: 'Hovering the mouse shows the full name.' }
    ],
    '4': [
      { q: 'Which is NOT a source or resource folder in a LUPA application project?',
        options: ['ui', 'res', 'src', 'bin'],
        hint: 'The bin folder is not part of the basic project structure.' },
      { q: 'Which is NOT an app attribute specified in the manifest file?',
        options: ['Pre/post install commands', 'App type', 'App category', 'App execution style'],
        hint: 'Pre/post install commands are specified in the spec.ini file.' },
      { q: 'What command format can be used in the spec.ini file?',
        options: ['Shell command', 'Python script', 'C++ code', 'JSON data'],
        hint: 'spec.ini supports only shell commands.' },
      { q: 'Which is a correct characteristic of APP_TYPE_PERSISTENT?',
        options: ['The developer controls the life cycle directly', 'It always stays in a running state', 'It runs only in the background', 'It exits when its work is done'],
        hint: 'The system manages the life cycle directly and it always stays running.' },
      { q: 'How is the life cycle of a LUPA application managed when no app type is specified?',
        options: ['The developer controls it directly', 'The app exits automatically', 'The system manages it automatically', 'The app does not run'],
        hint: 'Without a type, the developer must control the life cycle directly.' }
    ],
    '5': [
      { q: 'In the LUPA application package naming rule, which keyword is used for system apps?',
        options: ['sys', 'usr', 'core', 'app'],
        hint: 'System apps use the \u2018sys\u2019 keyword.' },
      { q: 'Which feature is used to create a project in LUPA Studio?',
        options: ['Project Wizard', 'Quick Launcher', 'meminfo', 'launch.json'],
        hint: 'Project creation is done through the Wizard.' },
      { q: 'In the LUPA application development procedure, at which step is UI work performed when needed?',
        options: ['After writing the service code', 'After debugging', 'After project creation', 'After building'],
        hint: 'UI work is the step right after project creation.' },
      { q: 'If a LUPA application package name is \u2018lupa.sys.meminfo\u2019, what kind of app is it?',
        options: ['A service app', 'A test app', 'A system app', 'A user app'],
        hint: 'The \u2018sys\u2019 keyword means a system app.' },
      { q: 'Which is NOT information you must check when building and running an app?',
        options: ['SDK version', 'Project selection', 'Install location', 'The app icon color'],
        hint: 'The app icon color is not required information.' }
    ],
    '6': [
      { q: 'Which combination of debugger and related tools is correct for device debugging in the LUPA development environment?',
        options: ['J-Link, OpenOCD, and gdb', 'OpenOCD, Visual Studio Code, and lupa-update-target-at-offset', 'gdb server, J-Link, and info files', 'J-Link, gdb server, and meminfo'],
        hint: 'Device debugging uses J-Link, OpenOCD, and gdb.' },
      { q: 'When debugging in the emulator environment, through what does gdb connect to the target device instead of OpenOCD?',
        options: ['The lupa-update-target-at-offset command', 'The port number of the gdb server', 'The meminfo command', 'The USB connection of J-Link'],
        hint: 'In the emulator environment, gdb connects directly to the gdb server by port number.' },
      { q: 'Which commands can be used to check the appOffset of a LUPA Application?',
        options: ['info files or gdb server', 'OpenOCD or J-Link', 'lupa-update-target-at-offset or meminfo', 'Visual Studio Code or LUPA Studio'],
        hint: 'The appOffset is checked with the lupa-update-target-at-offset command or the meminfo command.' },
      { q: 'What problem can occur if the symbol file load location in gdb does not match the appOffset?',
        options: ['Debugging does not work correctly', 'The device connection is lost', 'J-Link is not recognized', 'The gdb server terminates'],
        hint: 'If the appOffset and the symbol file load location differ, debugging does not work correctly.' },
      { q: 'Which gdb command is used in the debug console to check whether the symbol file load location matches the appOffset?',
        options: ['meminfo', 'info files', 'lupa-update-target-at-offset', 'openocd'],
        hint: 'In gdb, the info files command shows the symbol file load location.' }
    ],
    '7': [
      { q: 'Which is NOT included in the templates for Non-GUI service app development in LUPA Studio?',
        options: ['hello world', 'GUI design', 'empty project', 'event test'],
        hint: 'Non-GUI service templates do not include UI-related templates.' },
      { q: 'Which item cannot be configured in the project wizard?',
        options: ['App ID', 'SDK', 'Build target', 'Device IP'],
        hint: 'The project wizard does not set the device IP directly.' },
      { q: 'Which task can be performed in the SDK Manager?',
        options: ['Running apps', 'Connecting devices', 'Deleting apps', 'Activating SDKs'],
        hint: 'The SDK Manager provides SDK-related functions.' },
      { q: 'Which is NOT a correct way to check the execution result of a Non-GUI service app?',
        options: ['Using the DMESG command', 'Checking the UI screen directly', 'Checking console output', 'Using the LDB terminal'],
        hint: 'Non-GUI service apps do not display a UI screen.' },
      { q: 'Which command is NOT provided by the Quick Launcher?',
        options: ['Deleting apps', 'Clean', 'Configure', 'Build'],
        hint: 'The Quick Launcher provides build and execution related commands.' }
    ],
    '8': [
      { q: 'In the launch.json file, which configuration name must be added for LUPA device debugging?',
        options: ['run lupa-app', 'start lupa-debug', 'attach lupa-device', 'connect lupa-board'],
        hint: 'Add a configuration starting with attach. You can also debug with the \u2018Debug LUPA Device\u2019 configuration.' },
      { q: 'When using the J-Link device driver in LUPA development, through which tool must J-Link be connected for debugging?',
        options: ['VSCode', 'OpenOCD', 'GDB', 'DQC'],
        hint: 'It is the open-source debugging tool that connects to J-Link.' },
      { q: 'Which command must be run before debugging to save the app\u2019s offset information?',
        options: ['refresh-symbol-offset', 'set-debug-offset', 'update-target-offset', 'save-app-offset'],
        hint: 'It is the command starting with update.' },
      { q: 'The appOffset value stored in settings.json must match the result of which command for symbols to load correctly?',
        options: ['debug-info', 'symbol-list', 'meminfo', 'offset-check'],
        hint: 'It is the command that checks memory information.' },
      { q: 'In the Run and Debug tab, which device configuration must be selected to start debugging?',
        options: ['attach lupa-device', 'run lupa-app', 'connect lupa-board', 'start lupa-debug'],
        hint: 'It is the device configuration starting with attach. The \u2018Debug LUPA Device\u2019 configuration can also be selected.' }
    ]
  };

  /* ── 강의 원문 (data-sec 키) ─────────────────────────────── */
  var TR = {
    /* ch0 */
    '0': 'Hello. I am Kim Yun-Gwan, and I will be explaining LUPA Studio in this session.',
    '8': 'At the Platform Research Lab of the Software Center under the CTO division,',
    '11': 'and in the LUPA development environment task, I develop LUPA Studio.',
    '16': 'This LUPA Studio is a development tool used as the development environment',
    '22': 'for developing LUPA Applications or the platform.',
    '28': 'What I will introduce today — you have probably looked through it once in the pre-practice,',
    '35': 'but as a refresher, I will briefly introduce LUPA Studio,',
    '40': 'explain how it is used for LUPA development and what the LUPA development cycle looks like,',
    '45': 'describe the procedure of LUPA Application development,',
    '49': 'and focus on how LUPA Studio can be used for that.',
    '54': 'I look forward to working with you for the next two hours.',
    '57': 'First, before getting into LUPA Studio,',
    '61': 'there is a developer site that provides explanations and guides about the LUPA development environment.',
    '69': 'You can access it at lupa.lge.com or lupa.developer.lge.com.',
    '79': 'There you can check general information about LUPA platform development.',
    '87': 'And through a recent update, it now provides the LUPA AI chatbot service.',
    '94': 'If you look at the bottom right, there is a round icon; select it',
    '101': 'and you can get information about LUPA development in general by querying the AI agent.',
    '110': 'Likewise, that icon can also be used through the chat feature of VS Code inside LUPA Studio.',
    /* ch1 */
    '120': 'I will explain this again later in the latter part.',
    '123': 'LUPA Studio is a development environment based on VS Code, Visual Studio Code,',
    '134': 'and it has overall development environments and tools to support the LUPA Application development process.',
    '141': 'Because it is provided as an Extension,',
    '145': 'when you run VS Code on the left,',
    '149': 'you can select the LUPA Studio icon in the Activity Bar on the left and use its features.',
    '157': 'The screen shown here is the representative screen you see when you first run Visual Studio Code.',
    '168': 'You have probably encountered it a lot through the pre-study,',
    '174': 'or recently while using it in your development work.',
    '181': 'What we will focus on are the LUPA Studio menus in the Activity Bar and Side Bar on the left.',
    '188': 'You can check output through the console in the Output Panel at the bottom or the Output Channel.',
    '197': 'When you first run LUPA Studio and select the Activity Bar,',
    '207': 'the basic items of LUPA Studio appear on the left.',
    '213': 'At the very top is the SDK Manager.',
    '216': 'The SDK Manager is where, when developing on the LUPA platform,',
    '220': 'you select which target\u2019s development libraries will be built together into the app.',
    '227': 'And the second tab is the Device Manager.',
    '230': 'The Device Manager is used when using a real device or an Emulator:',
    '234': 'when installing or running an application, it decides which port or device to use.',
    '240': 'The LUPA Repository is an item for when you need to reference or use platform code during actual application development.',
    '253': 'This part was updated recently, but since a new version has not been released yet, the material has not been updated.',
    '264': 'The Quick Launcher is a menu that gathers frequently used commands related to building, installing, or running applications during LUPA development for easy one-click access.',
    '278': 'At the very bottom there is an item called the GUI Library Manager.',
    '283': 'We will not cover this in this certification training, but there is a LUPA Application UI authoring tool called GUI Creator, and this item collects the GUI libraries used there.',
    '302': 'At the very bottom is the LUPA Studio Status Bar, which displays the project you are currently working on, the selected SDK or target device, and the selected target platform build names.',
    '324': 'The term may be unfamiliar, but the target platform is a menu for selecting the target platform made up of the products — which category, refrigerator or washing machine — and chipsets of the product you want to develop or build.',
    '342': 'And at the far right, you can also select the build mode that chooses Debug and Release modes.',
    '351': 'The SDK Manager, as I explained earlier, is being used for user development.',
    /* ch2 */
    '360': 'It is about which SDK to choose for LUPA.',
    '364': 'In this SDK item, the application libraries can differ depending on the platform build,',
    '374': 'and the LUPA platform currently has several versions.',
    '378': 'There is the 1.1 LTS version,',
    '380': 'the 1.2 version, and broadly the 2.6 version.',
    '385': 'In today\u2019s practice, the course will use only the 1.2 version.',
    '393': 'Because the SDK contents and build versions differ per version,',
    '398': 'every time you develop an application you need to pay attention to this and select it.',
    '406': 'If you right-click on each item,',
    '412': 'you can download or install and activate it, deciding whether it is actually used in the build.',
    '423': 'An installed SDK is displayed with an \u201cinstalled\u201d label,',
    '428': 'and when you activate an installed SDK for use, the label changes to \u201cActivated\u201d.',
    '439': 'Although not covered in this course,',
    '442': 'when you build or use actual LUPA platform code inside LUPA Studio via the LUPA Repository,',
    '450': 'when you build the platform code and generate an SDK,',
    '453': 'you can copy that SDK into LUPA Studio, back it up, and use it directly.',
    '460': 'In that case, it is added under the Custom SDK item at the bottom and can be used.',
    '469': 'The files used by LUPA Studio are mostly under your user directory in a folder called .lupastudio,',
    '480': 'with lupa-sdk inside that folder.',
    '483': 'If you ever need to modify files related to the target device',
    '487': 'or such,',
    '490': 'you can find and check them at that location.',
    '498': 'And LUPA Studio',
    '500': 'likewise provides an Emulator feature.',
    '503': 'In the early days of LUPA development,',
    '507': 'because the Emulator versions that ran differed',
    '510': 'depending on each SDK or platform version,',
    '514': 'the UI was not generic,',
    '518': 'and each SDK and Emulator worked as a pair.',
    '522': 'That is how it used to work,',
    '523': 'but now the platform has stabilized a lot,',
    '527': 'so a single Emulator version can be used.',
    '530': 'The UI you see now, where the SDK and Emulator are',
    '533': 'paired together,',
    '536': 'you can think of as the old development process.',
    '543': 'If you right-click on the Emulator item',
    '546': 'or hover the mouse over it,',
    '548': 'run and stop buttons are displayed.',
    '553': 'There you select the SDK,',
    '556': 'then select the Emulator,',
    '558': 'and press the run button,',
    '559': 'and as you see on the right,',
    '561': 'the Emulator launches with three windows.',
    '565': 'The Emulator provides an environment where you can',
    '569': 'easily install an app and test it',
    '570': 'when there is no target device or in environments where one cannot be used.',
    '574': 'That is the kind of environment it provides.',
    '577': 'Three windows actually open:',
    '579': 'at the very bottom there is the',
    '582': 'GDC window where the UI is displayed.',
    '584': 'At the very top,',
    '586': 'the terminal called Renode',
    '589': 'is the console where the engine runs',
    '590': 'to execute the Emulator.',
    '593': 'Since this part is hardly used,',
    '594': 'you do not need to worry about it.',
    '597': 'The terminal in the middle called UART0',
    '600': 'outputs the system logs printed while the target Emulator runs, or provides a screen where you can connect directly to the console',
    '610': 'and enter input on the screen.',
    '613': 'The LUPA Emulator automatically changes the emulator image',
    '623': 'depending on which target chipset is selected — DQ-C or ITE type.',
    '628': 'To enable this, in the user settings section',
    '639': 'there is an item called Enable User Emulator in LUPA Studio.',
    '644': 'This is checked by default,',
    '646': 'but if you change the SDK',
    '649': 'or if you select and use a custom SDK,',
    '653': 'or after building the LUPA platform directly',
    '656': 'and connecting it, you can run the Emulator with',
    '660': 'the LUPA platform image you built yourself.',
    '664': 'That is the item used for that.',
    '667': 'The way to actually select the image is',
    '671': 'to Activate the SDK you want to use,',
    '677': 'and then run the Emulator. To check whether',
    '679': 'the target build you selected is properly selected,',
    '684': 'when you select the target name in the Status Bar at the bottom,',
    '689': 'a Quick Select screen appears at the top,',
    '693': 'and to the right of each target name a label called',
    '698': 'debug available is displayed.',
    '701': 'In that case, it means the user Emulator',
    '703': 'can be launched.',
    '710': 'When other images are selected,',
    '714': 'there is no image capable of running the Emulator,',
    '720': 'df.build.sk',
    '723': 'Device Manager',
    '731': 'Because the LUPA development environment uses serial ports,',
    '736': 'it usually uses COM ports.',
    '740': 'An Emulator can also be a device on a COM port.',
    '745': 'Occasionally, you may connect and use not one but two devices,',
    '752': 'and in that case, to distinguish the ports, you can name them and manage them in the Device Manager.',
    '760': 'Also, when actually using serial ports, it is not easy to check',
    '767': 'which serial port a LUPA device is connected to.',
    '773': 'In that case, press the Add Device button in the device list, enter a device name, and select a port.',
    '781': 'The port list shows the target devices currently connected to serial ports,',
    '788': 'and if there is a device connected to LUPA that can use LDB,',
    '794': 'a label called LDB is added in front of the device name.',
    '799': 'That way you can easily find where the LUPA device is connected.',
    '804': 'Likewise, if a port where LUPA commands can be used is already registered on the connected device,',
    '812': 'an \u201conline\u201d indication is displayed, as you see on screen when powered on.',
    '820': 'Occasionally the port changes due to device driver issues.',
    '827': 'If you connected the device but the port you used before does not show \u201conline\u201d,',
    '832': 'refresh in the Device Manager, or since the port may have changed,',
    '838': 'add the device again with Add Device.',
    '840': 'You can add it and select it.',
    '843': 'When a device is connected, you can perform several additional actions.',
    '850': 'You can install an application, run the app, or',
    '856': 'run Execute meminfo, a command to view the memory status of the actual target device.',
    '863': 'The dump register and memory items below it',
    '870': 'are menus that can only be run in debug mode with gdb connected, not in normal situations.',
    '875': 'When you run meminfo, it shows',
    '884': 'the memory situation — where the app on the target device is mapped in memory addresses.',
    '890': 'You can use this later for application debugging or checking whether installation succeeded.',
    '897': 'And on this LUPA target device you can use the LDB command.',
    '907': 'In the context menu — not shown in this figure, the figure is a bit out of date —',
    '913': 'you can run a command called show LDB log terminal.',
    '918': 'This is the terminal for actually running LDB commands and printing the results on screen.',
    '926': 'When you run the actual LDB log terminal, since the original LDB command',
    '932': 'runs as a Python program, you would have to enter the Python path, the LDB location,',
    '938': 'the COM port, and parameters one by one, but here,',
    '943': 'through an alias, you can simply enter LDB, the COM port, and the command you want',
    '951': 'to run LDB commands more easily from the host.',
    '961': 'What is shown here briefly demonstrates how the serial port is displayed when actually adding a device.',
    '970': 'When adding an online LDB device, press the Add Device button, enter the device name, and a list of ports connected to the current host appears.',
    '981': 'Among them, if a device that can use LDB is connected, \u201cLDB\u201d is displayed right at the front.',
    '994': 'This Repository View is the menu used when working with platform sources.',
    '999': 'You probably will not use this menu in this certification course, and will only reference sample sources later when debugging.',
    '1016': 'This menu is used when building the platform or downloading platform code.',
    '1027': 'In the LUPA Repository View there is an Add Repository button with a plus mark on the right.',
    '1032': 'There you can register the actual LUPA platform code inside LUPA Studio and use it.',
    '1042': 'To distinguish versions and such, naming is done via the Git Head.',
    '1051': 'This way you can register it via Register SDK.',
    '1057': 'Register SDK is the feature that brings an SDK built from registered platform code into LUPA Studio for use.',
    '1070': 'Likewise, since this LUPA platform code also builds an SDK and has target images, it can be used for application development builds.',
    '1080': 'In that case, with the Set Activate command, same as for an SDK, you can use the built SDK directly for app development.',
    '1090': 'If, when debugging, the built environment and the host environment you are developing on differ,',
    '1103': 'the debugger cannot find the source you want and the screen shows only blank pages.',
    '1112': 'In that case, copy the sources to the host and adjust the changed paths using the Set Debug Source Root command.',
    '1123': 'This part cannot be used right now because the source currently uploaded is slightly different,',
    '1133': 'but during the course we will adjust it so you can use it when you debug yourselves.',
    '1141': 'Likewise, Activate as a LUPA Project is a command that treats the platform itself as a single project and performs builds or debugging.',
    '1161': 'Since this is a menu for platform development rather than actual app development, we will skip it.',
    /* ch3 */
    '1168': 'Next is the Quick Launcher. The Quick Launcher is a set of shortcut icons gathering frequently used commands in one place.',
    '1182': 'Depending on the command, some require specific conditions or execution conditions.',
    '1189': 'For example, build or compilation can be used immediately without special conditions as long as a project is selected,',
    '1198': 'an SDK is selected,',
    '1200': 'and so on.',
    '1203': 'However, install or Start Application',
    '1207': 'only run when a target is designated and there is a runnable app.',
    '1211': 'Those are the items that require that.',
    '1215': 'Likewise for Uninstall.',
    '1217': 'In the case of Start Application,',
    '1220': 'it selects and runs a User App on the selected target.',
    '1225': 'If there are multiple User Apps,',
    '1227': 'there are cases where you must select the app to run in the Quick Pick screen.',
    '1235': 'Usually, when a project is selected, the app built from that project is run first.',
    '1243': 'The dump memory and dump register commands are used when debugging.',
    '1251': 'When currently connected in debug mode — in the debug state —',
    '1255': 'this feature dumps and downloads memory from the target device.',
    '1262': 'Because it is a dump feature, start and end addresses are needed as parameters,',
    '1268': 'and the actual save location is the currently selected project folder.',
    '1274': 'Likewise, register is a feature that downloads what register values are in the target device.',
    '1283': 'It is usually used when you want to record each register while the program is halted using gdb.',
    '1293': 'Likewise it is saved in text file format, and the inside is in JSON format.',
    '1298': 'You can use it when needed.',
    '1301': 'When there are frequently used global variables or values you want to monitor,',
    '1308': 'you can set and designate them here.',
    '1314': 'Then, when there are variables designated in the settings and you run dump register,',
    '1320': 'the values of those variables are downloaded and saved together.',
    '1324': 'And the status bar is a feature that displays information related to the LUPA development environment at once.',
    '1337': 'It shows the various settings selected at the bottom.',
    '1341': 'At the very front is the LUPA project name.',
    '1344': 'Next, a small monitor icon is displayed, followed by the device name.',
    '1352': 'After the device name there are parentheses, inside which the name of the currently active SDK is displayed.',
    '1360': 'To the right of the closing parenthesis, the target name is displayed.',
    '1366': 'The target name usually follows the format of the LUPA platform.',
    '1370': 'The target project name comes first,',
    '1373': 'then the chipset name, and after the chipset there is the target indicating which product variant it is.',
    '1383': 'Each item is separated by dots; for example, for the reference platform typically',
    '1389': 'the target name is distinguished like reference.dqc.nextosp.',
    '1396': 'Here the screen — products can be of many kinds, such as washers.',
    '1405': 'Here you can confirm this firmly by trying it yourselves.',
    '1417': 'Usually, when debugging symbols are included, when selecting the target name, at the back',
    '1422': 'an item called debug available is displayed.',
    '1426': 'This is displayed when debugger symbol ELF files and such are included.',
    '1433': 'For the others, symbols are not displayed when debugging,',
    '1440': 'so when debugging, always check that the target selection is correct.',
    '1450': 'Because product names are long, the status bar displays them abbreviated.',
    '1458': 'To check the actual value, hover the mouse and wait a moment, and the full name is displayed.',
    '1466': 'As additions, build icons are displayed.',
    '1475': 'Behind the build configuration, in the shape of a wrench, the command to build the LUPA application is included as a shortcut icon.',
    '1486': 'On the right, likewise, a LUPA application shortcut icon has been added.',
    '1493': 'The build configuration mostly uses release mode only.',
    '1500': 'Since the platform has so many product families, development does not proceed by separating debug and release modes; usually development proceeds only in release mode.',
    '1513': 'I do not have much more to say about that.',
    '1527': 'Among the views that can be opened in LUPA Studio, there is the API guide viewer.',
    '1542': 'While developing actual LUPA applications, you will often need to look up or reference APIs.',
    '1550': 'In that case, press Ctrl-Shift-P to open the command palette and run it there,',
    '1558': 'run LUPA API,',
    '1560': 'and when you run the API guide viewer, you can check the API guide matching the selected SDK version directly in the editor.',
    '1569': 'The entire API guide is listed here,',
    '1573': 'but since it is not easy to find the API you want here, you can use various other methods.',
    '1580': 'For example, you can find the API guide in chat, or check it via chat on the developer site I showed you at the beginning.',
    '1591': 'Likewise, this API guide is distributed the same way on the developer site.',
    '1597': 'If you look at the Output panel now, there is a feature called the LDB terminal.',
    '1609': 'It is similar to the LDB terminal we used on the LUPA device explained earlier.',
    '1618': 'While the LDB terminal opened in the device manager shows all the LDB logs run by LUPA Studio,',
    '1629': 'the terminal in this Output panel does not show output; it is used when you run LDB commands directly yourself.',
    '1642': 'Select the terminal in the view below, press the dropdown button in the pane below the terminal,',
    '1648': 'and inside, various kinds of terminals available on the host appear.',
    '1653': 'Among them, if you select LDB, you can likewise easily run LDB commands via the LDB alias.',
    '1661': 'And LUPA Studio likewise supports the remote development environment supported by VS Code.',
    '1672': 'Since LUPA platform development is mostly done on Linux, usually on a remote system...',
    '1680': 'there are many cases of continuing development. However, when developing on a remote system, some host features cannot be used.',
    '1689': 'Usually opening a project or building can be done on the host, but when an actual target device is connected,',
    '1699': 'since the serial port is connected only to the host, it cannot be used from the remote side.',
    '1705': 'Some people in the Home Appliance business division connect a LUPA device directly to a remote system they connect to remotely',
    '1710': 'and directly install there, or',
    '1718': 'install and run on the target device — some people do that occasionally.',
    '1723': 'You can maintain and use the environment that way,',
    '1731': 'but basically, remember only this: only building is possible.',
    /* ch4 */
    '1740': 'Let me briefly look at the LUPA application project.',
    '1751': 'What I am explaining here is explicitly labeled a LUPA GUI application,',
    '1755': 'but you can think of the structure of LUPA applications as being the same.',
    '1766': 'The LUPA platform uses packages with the extension LPK as applications.',
    '1773': 'This package file contains the built binaries together with resource files.',
    '1780': 'The actual sources are below: src, and res which holds resources.',
    '1787': 'Most importantly, it has CMake files, manifest files, spec,',
    '1794': 'and various other configuration files.',
    '1798': 'The folder called ui',
    '1800': 'is the folder where files related to the UI created with GUI Creator go.',
    '1807': 'The manifest file used in this LUPA application',
    '1811': 'has various attributes for the application being installed,',
    '1815': 'for the application being developed.',
    '1817': 'It has various attributes.',
    '1824': 'In these attributes you can specify',
    '1827': 'the category and the app type.',
    '1829': 'Usually the category specifies the kind of app',
    '1833': 'and determines in which category the app will run.',
    '1839': 'The app type can be used',
    '1842': 'in a form that turns keywords On/Off',
    '1844': 'by type name.',
    '1846': 'Depending on the type name, how the app runs',
    '1850': 'and the life cycle it operates with change.',
    '1855': 'And there is a file called spec.ini.',
    '1859': 'This is a file with features that let you add',
    '1864': 'certain commands when the application is installed or removed.',
    '1868': 'On the right you can see pre_install, post_install,',
    '1872': 'pre_uninstall, post_uninstall —',
    '1875': 'four items.',
    '1877': 'As the names say, they specify what commands to run on the target',
    '1879': 'before installing,',
    '1881': 'or after installing,',
    '1883': 'what commands to run on the target,',
    '1885': 'specified in shell command item format.',
    '1889': 'They are mainly used when something needs to be changed in settings before or after installation,',
    '1896': 'or when commands need to change settings.',
    '1900': 'That is the main use.',
    '1902': 'The example here shows a command added that, after installation,',
    '1906': 'changes a certain item of settings',
    '1909': 'to a specific value.',
    '1911': 'That is an example of an added command.',
    '1914': 'Note that the spec.ini file',
    '1916': 'is included together inside the package file,',
    '1920': 'so if too many commands are included, errors can occur when building',
    '1926': 'because the size grows.',
    '1928': 'Usually only one or two lines of commands can be added.',
    '1933': 'I briefly mentioned that these applications have different life cycles depending on type.',
    '1943': 'Usually there are three representative types.',
    '1946': 'The items are whether the app type is APP_TYPE_PERSISTENT, APP_TYPE_BACKGROUND, or APP_TYPE_IMMORTAL.',
    '1954': 'There are also cases where none of these three types is specified.',
    '1959': 'When no type is specified, the app does not follow a separate life cycle,',
    '1964': 'and through the Start app or Stop app that developers enter directly,',
    '1969': 'you can define the app\u2019s life cycle.',
    '1974': 'APP_TYPE_PERSISTENT apps always maintain a running state,',
    '1979': 'cannot be terminated or started directly from outside,',
    '1983': 'and are applications whose life cycle is managed directly by the platform.',
    '1990': 'An app that is always running in one category is called APP_TYPE_PERSISTENT.',
    '1996': 'It usually runs only when the product is powered on',
    '2001': 'and is the type of app that terminates when powered off.',
    '2006': 'And APP_TYPE_BACKGROUND',
    '2010': 'refers to applications that keep running in the background.',
    '2014': 'Without special termination conditions or explicit restart specifications,',
    '2017': 'think of it as a background service that always runs while the power is on.',
    '2023': 'APP_TYPE_IMMORTAL is similar to background,',
    '2028': 'but it is an app that terminates itself when its work is complete.',
    '2033': 'You can think of it that way.',
    '2038': 'Likewise, it is an app always running in the background.',
    '2042': 'And the background is organizing the power.',
    '2046': 'And the background is organizing the power.',
    '2050': 'And the background is organizing the power.',
    '2054': 'And the background is organizing the power.',
    '2040': 'It is an app that is always in an operating state.',
    '2045': 'Because it cannot be terminated or restarted arbitrarily,',
    '2049': 'you must specify the actions for that.',
    '2053': 'Those are the representative application types.',
    '2057': 'Probably, during development,',
    '2060': 'you will mostly use it without specifying a type,',
    '2064': 'or run it only as an APP_TYPE_BACKGROUND service',
    '2066': 'via APP_TYPE_BACKGROUND.',
    '2069': 'That is how it will mostly be used.',
    '2075': 'This table shows, for each type,',
    '2078': 'how the start and stop commands',
    '2080': 'behave,',
    '2082': 'organized into one table.',
    '2085': 'When there is no app type, there is no start timing,',
    '2088': 'so the user must always run it directly.',
    '2091': 'Likewise, since there is no termination condition either,',
    '2095': 'you must terminate it directly.',
    '2097': 'For the others — APP_TYPE_PERSISTENT, APP_TYPE_BACKGROUND,',
    '2099': 'APP_TYPE_IMMORTAL —',
    '2101': 'they have termination conditions designated by the system.',
    '2111': 'This LUPA configuration',
    '2117': 'can be edited directly in the file, but',
    '2121': 'it can also be edited through a view called project configuration.',
    '2125': 'You can edit it that way.',
    '2127': 'In the Command Palette,',
    '2129': 'if you search for LUPA project configuration,',
    '2135': 'an editor for editing the configuration of',
    '2136': 'the selected project appears.',
    '2140': 'On the right side of the editor,',
    '2141': 'the description shows explanations for each item.',
    '2146': 'The application types I just mentioned,',
    '2152': 'the version, and other information about manifest.json',
    '2156': 'are additionally displayed.',
    '2157': 'When needed, you can use it like a help guide.',
    /* ch5 */
    '2160': 'The actual procedure for developing such an application is as follows.',
    '2170': 'The parts marked in red are unnecessary for Non-GUI applications.',
    '2176': 'You create the actual LUPA project, do UI work if there is a UI,',
    '2181': 'then write the code for the remaining service part excluding the UI,',
    '2188': 'build the app, run it, debug when there are problems, and develop by repeating this process.',
    '2196': 'When actually building and running the app, the LPK file or the package name is used.',
    '2206': 'It is not marked separately here — is it in the back?',
    '2210': 'The package name has an explicitly designated format.',
    '2215': 'It starts with lupa, a dot, then the application kind — whether it is a user app, a system app, or a platform service.',
    '2225': 'A three-letter keyword designates that.',
    '2228': 'After that, the application name or service names are specified.',
    '2233': 'In this format, there is a naming rule for the package name or application name.',
    '2242': 'Usually, when you first create a LUPA project, LUPA Studio provides the Project Wizard.',
    '2249': 'I will explain the Project Wizard again later, so let us move on for now.',
    '2255': 'And when doing GUI design, you can run GUI Creator to do it,',
    '2261': 'and although it is included in the material later, you probably will not use it in this course,',
    '2268': 'so just think of it as something that exists for reference.',
    '2280': 'Ah, it is written here.',
    '2282': 'The LUPA platform has several system apps included by default.',
    '2288': 'Apps that perform essential functions for the product are called system apps or platform apps.',
    '2295': 'The LUPA package names shown here, as I said, follow the format lupa.sys.projectapplication-name.',
    '2305': 'System apps include \u201csys\u201d and user apps include \u201cusr\u201d as the keyword.',
    '2312': 'Each has different categories and states according to its role.',
    '2318': 'When you are curious about these, you can use the meminfo I mentioned at the beginning to check which apps are running in memory and which are installed.',
    '2330': 'Usually the built-in apps included in the platform unit are the system apps.',
    '2337': 'In the platform code, in the product specification section, you can configure differently per product which apps are included.',
    '2355': 'After this, there is a guide on actually installing LUPA Studio.',
    '2361': 'First, since LUPA Studio is based on Visual Studio Code, Visual Studio Code must always be installed first.',
    '2367': 'Recently, as many AI features have been updated in Visual Studio Code, the update cycle has become very short.',
    '2378': 'A year ago it was updated once a quarter or once every six months, but nowadays, in severe cases, a version is updated and released every week.',
    '2391': 'Presumably because people use AI a lot — because many use AI agents —',
    '2400': 'keeping the latest version as much as possible seems to be a way to apply the latest features quickly.',
    '2408': 'LUPA Studio can be installed via the Visual Studio Code Extension Package.',
    '2419': 'Through the developer mailing list, a notification mail is sent whenever the version is updated.',
    '2426': 'The version is currently at update 9, and an update is expected soon.',
    '2439': 'LUPA Studio supports automatic updates, so once installed, when a version is updated it shows a message box asking whether to update.',
    '2454': 'If you want the update, proceed with it directly; if you decide it is not needed, you can keep the current version.',
    '2470': 'Since LUPA Studio also plans to use AI features later, keeping it up to date will help a lot, I believe.',
    '2482': 'Usually, looking at the LUPA app development cycle I mentioned earlier, there is a part where you create the project.',
    '2493': 'When creating a new project, using the LUPA Project Wizard is recommended.',
    '2500': 'You can run the LUPA Project Wizard through the Command Palette.',
    '2505': 'After selecting the project location and template, you can enter information about the LUPA app and create it.',
    '2512': 'It is not shown here, so let us skip this part.',
    '2520': 'Since this is about writing GUI applications, let us skip it briefly. Let me update the configuration for a moment.',
    '2538': 'Since this part is GUI-related, we skip it, and I will briefly explain only building and running this LUPA application.',
    '2558': 'The most essential information when building is whether the current project is selected, which SDK version is used, and where to install and run the built LPK file.',
    '2574': 'These three pieces of information are essential. If you say you will only build without installing, you need to select only the project and the SDK.',
    '2585': 'For the app you wrote to run correctly on the target, when selecting the SDK in lupa-chooser you need to care about compatibility with the target chipset name and product.',
    '2602': 'An application built with the 2.0 SDK does not run on 1.1. Work with version compatibility in mind like this.',
    '2618': 'Building and running this LUPA application can be done in one step, and you can run it directly via the Launch Configuration called Run Without Debugging.',
    '2631': 'Usually, in Visual Studio Code, scripts related to running and debugging',
    '2640': 'are designated in a configuration file called launch.json.',
    '2645': 'If you add the LUPA-related launch configuration there,',
    '2650': 'you can perform tasks related to LUPA build, execution, and debugging like this.',
    '2660': 'When building manually, in LUPA Studio\u2019s Quick Launcher you can do the same work by running Clean, Configure, Build, etc. in order.',
    '2675': 'This launch configuration part can be checked in Visual Studio Code by selecting the Run and Debug panel on the left.',
    '2687': 'In the Run & Debug item menu at the very top, in the dropdown box at the top, you can decide which launch configuration to select and run.',
    '2699': 'There are three basic configurations provided by LUPA Studio.',
    '2704': 'The first is a simple configuration called LUPA, Launch LUPA app.',
    '2712': 'This configuration selects whether to run debugging or run app installation, depending on the target and action.',
    '2723': 'Possible targets are actual devices, and it works the same on the Emulator.',
    '2729': 'Pressing F5 is a shortcut to start debugging,',
    '2733': 'and pressing Ctrl+F4 is the install command, so it first runs the build and then proceeds all the way to installing on the selected target in one go.',
    '2748': 'To actually debug, change this configuration to Debug LUPA, Device, or Emulator, or depending on experience,',
    '2760': 'select configurations such as dbg-lupa, attach-lupa-device, attach-lupa-emulator',
    '2765': 'and proceed with development.',
    '2770': 'What is shown here briefly demonstrates an example of adding a configuration.',
    '2781': 'It is included because for those installing for the first time or doing it for the first time,',
    '2787': 'the process can be confusing.',
    '2791': 'After actually creating a brand-new empty project,',
    '2795': 'since the launch configuration is empty,',
    '2800': 'enter Run & Debug mode, select the launch.json file,',
    '2808': 'and you can add a new configuration.',
    '2811': 'The most basic one is the item called lupa-studio-app-launcher.',
    '2816': 'Besides that, open the launch.json file directly',
    '2822': 'and press shift-space to enable auto-completion,',
    '2827': 'then, as in the screenshot at the bottom left, through filtering',
    '2832': 'you can add the compilation you want.',
    '2836': 'It is hard to see because of the clock display; you can refer to it.'
  };

  return { UI: UI, CH_TITLE: CH_TITLE, CH_GOALS: CH_GOALS, CH_KEYS: CH_KEYS, QUIZ: QUIZ, TR: TR };
})();
